library_dict = {
    "10Xv1_3": {
        "Comment[cDNA read offset]": "0",
        "Comment[cDNA read]": "read2",
        "Comment[cell barcode offset]": "0",
        "Comment[cell barcode read]": "read1",
        "Comment[cell barcode size]": "14",
        "Comment[end bias]": "3 prime tag",
        "Comment[input molecule]": "polyA RNA",
        "Comment[library construction]": "10xV1",
        "Comment[LIBRARY_LAYOUT]": "PAIRED",
        "Comment[LIBRARY_SELECTION]": "cDNA",
        "Comment[LIBRARY_SOURCE]": "TRANSCRIPTOMIC SINGLE CELL",
        "Comment[LIBRARY_STRAND]": "first strand",
        "Comment[LIBRARY_STRATEGY]": "RNA-Seq",
        "Comment[primer]": "oligo-dT",
        "Comment[sample barcode offset]": "0",
        "Comment[sample barcode read]": "index1",
        "Comment[sample barcode size]": "8",
        "Comment[single cell isolation]": "10x technology",
        "Comment[umi barcode offset]": "14",
        "Comment[umi barcode read]": "read1",
        "Comment[umi barcode size]": "10",
        "Material Type_2": "RNA",
        "Technology Type": "sequencing assay"
    },
    "10Xv1_5": {
        "Comment[cDNA read offset]": "0",
        "Comment[cDNA read]": "read2",
        "Comment[cell barcode offset]": "0",
        "Comment[cell barcode read]": "read1",
        "Comment[cell barcode size]": "14",
        "Comment[end bias]": "5 prime tag",
        "Comment[input molecule]": "polyA RNA",
        "Comment[library construction]": "10xV1",
        "Comment[LIBRARY_LAYOUT]": "PAIRED",
        "Comment[LIBRARY_SELECTION]": "cDNA",
        "Comment[LIBRARY_SOURCE]": "TRANSCRIPTOMIC SINGLE CELL",
        "Comment[LIBRARY_STRAND]": "first strand",
        "Comment[LIBRARY_STRATEGY]": "RNA-Seq",
        "Comment[primer]": "oligo-dT",
        "Comment[sample barcode offset]": "0",
        "Comment[sample barcode read]": "index1",
        "Comment[sample barcode size]": "8",
        "Comment[single cell isolation]": "10x technology",
        "Comment[umi barcode offset]": "14",
        "Comment[umi barcode read]": "read1",
        "Comment[umi barcode size]": "10",
        "Material Type_2": "RNA",
        "Technology Type": "sequencing assay"
    },
    "10Xv2_3": {
        "Comment[cDNA read offset]": "0",
        "Comment[cDNA read]": "read2",
        "Comment[cell barcode offset]": "0",
        "Comment[cell barcode read]": "read1",
        "Comment[cell barcode size]": "16",
        "Comment[end bias]": "3 prime tag",
        "Comment[input molecule]": "polyA RNA",
        "Comment[library construction]": "10xV2",
        "Comment[LIBRARY_LAYOUT]": "PAIRED",
        "Comment[LIBRARY_SELECTION]": "cDNA",
        "Comment[LIBRARY_SOURCE]": "TRANSCRIPTOMIC SINGLE CELL",
        "Comment[LIBRARY_STRAND]": "first strand",
        "Comment[LIBRARY_STRATEGY]": "RNA-Seq",
        "Comment[primer]": "oligo-dT",
        "Comment[sample barcode offset]": "0",
        "Comment[sample barcode read]": "index1",
        "Comment[sample barcode size]": "8",
        "Comment[single cell isolation]": "10x technology",
        "Comment[umi barcode offset]": "16",
        "Comment[umi barcode read]": "read1",
        "Comment[umi barcode size]": "10",
        "Material Type_2": "RNA",
        "Technology Type": "sequencing assay"
    },
    "10Xv2_5": {
        "Comment[cDNA read offset]": "0",
        "Comment[cDNA read]": "read2",
        "Comment[cell barcode offset]": "0",
        "Comment[cell barcode read]": "read1",
        "Comment[cell barcode size]": "16",
        "Comment[end bias]": "5 prime tag",
        "Comment[input molecule]": "polyA RNA",
        "Comment[library construction]": "10xV2",
        "Comment[LIBRARY_LAYOUT]": "PAIRED",
        "Comment[LIBRARY_SELECTION]": "cDNA",
        "Comment[LIBRARY_SOURCE]": "TRANSCRIPTOMIC SINGLE CELL",
        "Comment[LIBRARY_STRAND]": "first strand",
        "Comment[LIBRARY_STRATEGY]": "RNA-Seq",
        "Comment[primer]": "oligo-dT",
        "Comment[sample barcode offset]": "0",
        "Comment[sample barcode read]": "index1",
        "Comment[sample barcode size]": "8",
        "Comment[single cell isolation]": "10x technology",
        "Comment[umi barcode offset]": "16",
        "Comment[umi barcode read]": "read1",
        "Comment[umi barcode size]": "10",
        "Material Type_2": "RNA",
        "Technology Type": "sequencing assay"
    },
    "10Xv3_3": {
        "Comment[cDNA read offset]": "0",
        "Comment[cDNA read size]": "98",
        "Comment[cDNA read]": "read2",
        "Comment[cell barcode offset]": "0",
        "Comment[cell barcode read]": "read1",
        "Comment[cell barcode size]": "16",
        "Comment[end bias]": "3 prime tag",
        "Comment[input molecule]": "polyA RNA",
        "Comment[library construction]": "10xV3",
        "Comment[LIBRARY_LAYOUT]": "PAIRED",
        "Comment[LIBRARY_SELECTION]": "cDNA",
        "Comment[LIBRARY_SOURCE]": "TRANSCRIPTOMIC SINGLE CELL",
        "Comment[LIBRARY_STRAND]": "first strand",
        "Comment[LIBRARY_STRATEGY]": "RNA-Seq",
        "Comment[primer]": "oligo-dT",
        "Comment[sample barcode offset]": "0",
        "Comment[sample barcode read]": "index1",
        "Comment[sample barcode size]": "8",
        "Comment[single cell isolation]": "10x technology",
        "Comment[umi barcode offset]": "16",
        "Comment[umi barcode read]": "read1",
        "Comment[umi barcode size]": "12",
        "Material Type_2": "RNA",
        "Technology Type": "sequencing assay"
    },
    "drop-seq": {
        "Comment[cDNA read offset]": "0",
        "Comment[cDNA read]": "read2",
        "Comment[cell barcode offset]": "0",
        "Comment[cell barcode read]": "read1",
        "Comment[cell barcode size]": "12",
        "Comment[end bias]": "3 prime tag",
        "Comment[input molecule]": "polyA RNA",
        "Comment[library construction]": "Drop-seq",
        "Comment[LIBRARY_LAYOUT]": "PAIRED",
        "Comment[LIBRARY_SELECTION]": "cDNA",
        "Comment[LIBRARY_SOURCE]": "TRANSCRIPTOMIC SINGLE CELL",
        "Comment[LIBRARY_STRAND]": "first strand",
        "Comment[LIBRARY_STRATEGY]": "RNA-Seq",
        "Comment[primer]": "oligo-dT",
        "Comment[sample barcode offset]": "",
        "Comment[sample barcode read]": "",
        "Comment[sample barcode size]": "",
        "Comment[single cell isolation]": "Drop-seq",
        "Comment[umi barcode offset]": "12",
        "Comment[umi barcode read]": "read1",
        "Comment[umi barcode size]": "8",
        "Material Type_2": "RNA",
        "Technology Type": "sequencing assay"
    },
    "smart-like": {
        "Comment[cDNA read offset]": "",
        "Comment[cDNA read]": "",
        "Comment[cell barcode offset]": "",
        "Comment[cell barcode read]": "",
        "Comment[cell barcode size]": "",
        "Comment[end bias]": "none",
        "Comment[input molecule]": "polyA RNA",
        "Comment[library construction]": "smart-like",
        "Comment[LIBRARY_LAYOUT]": "PAIRED",
        "Comment[LIBRARY_SELECTION]": "cDNA",
        "Comment[LIBRARY_SOURCE]": "TRANSCRIPTOMIC SINGLE CELL",
        "Comment[LIBRARY_STRAND]": "first strand",
        "Comment[LIBRARY_STRATEGY]": "RNA-Seq",
        "Comment[primer]": "oligo-dT",
        "Comment[sample barcode offset]": "",
        "Comment[sample barcode read]": "",
        "Comment[sample barcode size]": "",
        "Comment[single cell isolation]": "FACS",
        "Comment[umi barcode offset]": "",
        "Comment[umi barcode read]": "",
        "Comment[umi barcode size]": "",
        "Material Type_2": "RNA",
        "Technology Type": "sequencing assay"
    },
    "smart-seq": {
        "Comment[cDNA read offset]": "",
        "Comment[cDNA read]": "",
        "Comment[cell barcode offset]": "",
        "Comment[cell barcode read]": "",
        "Comment[cell barcode size]": "",
        "Comment[end bias]": "none",
        "Comment[input molecule]": "polyA RNA",
        "Comment[library construction]": "smart-seq2",
        "Comment[LIBRARY_LAYOUT]": "PAIRED",
        "Comment[LIBRARY_SELECTION]": "cDNA",
        "Comment[LIBRARY_SOURCE]": "TRANSCRIPTOMIC SINGLE CELL",
        "Comment[LIBRARY_STRAND]": "first strand",
        "Comment[LIBRARY_STRATEGY]": "RNA-Seq",
        "Comment[primer]": "oligo-dT",
        "Comment[sample barcode offset]": "",
        "Comment[sample barcode read]": "",
        "Comment[sample barcode size]": "",
        "Comment[single cell isolation]": "FACS",
        "Comment[umi barcode offset]": "",
        "Comment[umi barcode read]": "",
        "Comment[umi barcode size]": "",
        "Material Type_2": "RNA",
        "Technology Type": "sequencing assay"
    }
}

technology_dict = {
    "Fluidigm C1-based library preparation": "smart-like",
    "10X 3' v1": "10Xv1_3",
    "10X 5' v1": "10Xv1_5",
    "10X 3' v2": "10Xv2_3",
    "10X 5' v2": "10Xv2_5",
    "10X 3' v3": "10Xv3_3",
    "10X 3' v1 sequencing": "10Xv1_3",
    "10X 5' v1 sequencing": "10Xv1_5",
    "10X 3' v2 sequencing": "10Xv2_3",
    "10X 5' v2 sequencing": "10Xv2_5",
    "10X 3' v3 sequencing": "10Xv3_3",
    "10x 3' v1": "10Xv1_3",
    "10x 5' v1": "10Xv1_5",
    "10x 3' v2": "10Xv2_3",
    "10x 5' v2": "10Xv2_5",
    "10x 3' v3": "10Xv3_3",
    "10x 3' v1 sequencing": "10Xv1_3",
    "10x 5' v1 sequencing": "10Xv1_5",
    "10x 3' v2 sequencing": "10Xv2_3",
    "10x 5' v2 sequencing": "10Xv2_5",
    "10x 3' v3 sequencing": "10Xv3_3",
    "Drop-seq": "drop-seq",
    "inDrop": "drop-seq",
    "Smart-like": "smart-like",
    "Smart-seq2": "smart-seq",
    "Smart-seq": "smart-seq"
}

default_read_lengths = {
    "smart-like": {"read1": 75, "read2": 75},  # sometimes 100bp x 2
    "smart-seq": {"read1": 75, "read2": 75},
    "drop-seq": {"read1": 12, "read2": 60},
    "10Xv1_3": {"read1": 26, "read2": 98, "index1": 8},
    "10Xv1_5": {"read1": 26, "read2": 98, "index1": 8},
    "10Xv2_3": {"read1": 26, "read2": 98, "index1": 8},
    "10Xv2_5": {"read1": 26, "read2": 98, "index1": 8},
    "10Xv3_3": {"read1": 28, "read2": 91, "index1": 8}
}
