sdrf_map_all = {
    "standard": {
        "Characteristics[organism]": "donor_organism.genus_species.ontology_label",
        "Characteristics[individual]": "donor_organism.biomaterial_core.biomaterial_id",
        "Characteristics[sex]": "donor_organism.sex",
        "Characteristics[age]": "donor_organism.organism_age",
        "Unit[time unit]": "donor_organism.organism_age_unit.text",
        "Characteristics[developmental stage]": "donor_organism.development_stage.text",
        "Characteristics[organism part]": "specimen_from_organism.organ.ontology_label",
        "Characteristics[sampling site]": "specimen_from_organism.organ_parts.ontology_label",
        "Characteristics[cell type]": "cell_suspension.selected_cell_types.ontology_label",
        "Characteristics[disease]": "donor_organism.diseases.ontology_label",
        "Characteristics[organism status]": "donor_organism.is_living",
        "Characteristics[cause of death]": "donor_organism.death.cause_of_death",
        "Description": "specimen_from_organism.biomaterial_core.biomaterial_description",
    },
    "organoid": {
        "Characteristics[organism]": "donor_organism.genus_species.ontology_label",
        "Characteristics[individual]": "organoid.biomaterial_core.biomaterial_id",
        "Characteristics[sex]": "donor_organism.sex",
        "Characteristics[age]": "donor_organism.organism_age",
        "Unit[time unit]": "donor_organism.organism_age_unit.text",
        "Characteristics[developmental stage]": "donor_organism.development_stage.text",
        "Characteristics[organism part]": "specimen_from_organism.organ.ontology_label",
        "Characteristics[sampling site]": "specimen_from_organism.organ_parts.ontology_label",
        "Characteristics[cell line]": "organoid.biomaterial_core.biomaterial_name",
        "Characteristics[cell type]": "organoid.model_organ.ontology_label",
        "Characteristic[growth condition]": "cell_line.growth_conditions.growth_medium",
        "Characteristic[progenitor cell type]": "cell_line.cell_type.text",
        "Characteristics[disease]": "organoid.disease.ontology_label",
        "Characteristics[treatment]": "organoid.growth_conditions.drug_treatment",
        "Characteristics[organism status]": "donor_organism.is_living",
        "Characteristics[cause of death]": "donor_organism.death.cause_of_death",
        "Description": "organoid.biomaterial_core.biomaterial_description",
    },
    "cell_line": {
        "Characteristics[organism]": "donor_organism.genus_species.ontology_label",
        "Characteristics[individual]": "cell_line.biomaterial_core.biomaterial_id",
        "Characteristics[sex]": "donor_organism.sex",
        "Characteristics[age]": "donor_organism.organism_age",
        "Unit[time unit]": "donor_organism.organism_age_unit.text",
        "Characteristics[developmental stage]": "donor_organism.development_stage.text",
        "Characteristics[organism part]": "specimen_from_organism.organ.ontology_label",
        "Characteristics[sampling site]": "specimen_from_organism.organ_parts.ontology_label",
        "Characteristics[cell line]": "cell_line.biomaterial_core.biomaterial_name",
        "Characteristics[cell type]": "cell_line.model_organ.ontology_label",
        "Characteristic[growth condition]": "cell_line.growth_conditions.growth_medium",
        "Characteristic[progenitor cell type]": "cell_line.cell_type.text",
        "Characteristics[disease]": "cell_line.disease.ontology_label",
        "Characteristics[treatment]": "cell_line.growth_conditions.drug_treatment",
        "Characteristics[organism status]": "donor_organism.is_living",
        "Characteristics[cause of death]": "donor_organism.death.cause_of_death",
        "Description": "cell_line.biomaterial_core.biomaterial_description",
    },
    "cell_line_organoid": {
        "Characteristics[organism]": "donor_organism.genus_species.ontology_label",
        "Characteristics[individual]": "organoid.biomaterial_core.biomaterial_id",
        "Characteristics[sex]": "donor_organism.sex",
        "Characteristics[age]": "donor_organism.organism_age",
        "Unit[time unit]": "donor_organism.organism_age_unit.text",
        "Characteristics[developmental stage]": "donor_organism.development_stage.text",
        "Characteristics[organism part]": "specimen_from_organism.organ.ontology_label",
        "Characteristics[sampling site]": "specimen_from_organism.organ_parts.ontology_label",
        "Characteristics[cell line]": "cell_line.biomaterial_core.biomaterial_name",
        "Characteristics[cell type]": "organoid.model_organ.ontology_label",
        "Characteristic[growth condition]": "cell_line.growth_conditions.growth_medium",
        "Characteristic[progenitor cell type]": "cell_line.cell_type.text",
        "Characteristics[disease]": "organoid.disease.ontology_label",
        "Characteristics[treatment]": "organoid.growth_conditions.drug_treatment",
        "Characteristics[organism status]": "donor_organism.is_living",
        "Characteristics[cause of death]": "donor_organism.death.cause_of_death",
        "Description": "organoid.biomaterial_core.biomaterial_description",
    }
}
